FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MajesticThai

Polls is a simple API allowing consumers to view polls and vote in them.

## Menu Collection [/menu]

### Menu List [GET]

+ Response 200 (application/json)

            {    
            
                [
            
              
                    {
                        "id": 1
                        "item": "Spring Rolls",
                        "description": "Crisp vegetarian spring rolls, thai sweet and sour sauce.",
                        "price": 5000,
                        "category": "Appetizers"
                    }, {
                        "id": 2
                        "item": "Chicken Sa Tay",
                        "description": "Sliced chicken breast marinated in a misture of Thai sauce.",
                        "price": 6000,
                        "category": "Appetizers"
                    }, {
                        "id": 3
                        "item": "Yin Yang",
                        "description": "Crisp wontons filled with cream cheese.",
                        "price": 8000,
                        "category": "Appetizers"
                    }, {
                        "id": 4
                        "item": "Crisp Calamari",
                        "description": "Specially seasoned battered-fried calamari.",
                        "price": 3000,
                        "category": "Appetizers"
                    }, {
                        "id": 5
                        "item": "Famous Pad Thai",
                        "description": "Choice of chicken or pork stir-fried with rice noodles.",
                        "price": 3000,
                        "category": "Entree"
                    }, {
                        "id": 6
                        "item": "Thai Fried Rice",
                        "description": "Chicken or Beef stir-fried with jasmine rice.",
                        "price": 3000,
                        "category": "Entree"
                    }, {
                        "id": 7
                        "item": "Soft Shell Crab",
                        "description": "Golden-fried soft shell crabs.",
                        "price": 3000,
                        "category": "Entree"
                    }, {
                        "id": 8
                        "item": "Siam Catfish",
                        "description": "Specially seasoned battered-fried calamari.",
                        "price": 3000,
                        "category": "Entree"
                    }, {
                        "id": 9
                        "item": "Sticky Rice",
                        "description": "Really sticky rice.",
                        "price": 3000,
                        "category": "Dessert"
                    }, {
                        "id": 10
                        "item": "Green Tea Ice Cream",
                        "description": "Really cold green tea ice-cream, mmmmmmm.",
                        "price": 3000,
                        "category": "Dessert"
                    }
            
            
                ] 
        
            } 
        
        

## Menu Item [/dishes/{id}]

+ Parameters

    + id (number) - ID of the Question in the form of an integer

### View a Menu Item [GET]

+ Response 200 (application/json)



                    {
                        "id": 10
                        "item": "Green Tea Ice Cream",
                        "description": "Really cold green tea ice-cream, mmmmmmm.",
                        "price": 3000,
                        "category": "Dessert"
                    }